//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid bot = new Guid("96e24389-f27e-4ce7-a9cf-6dee36c3a8cc");
		public static readonly Guid uui = new Guid("9f31ee83-6f8e-44b7-ae16-3c60a4139f9a");

    }
}
