//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the Context Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace ffff
{
    using Apex.AI;

    public class BasicContext : IAIContext
    {
    }
}