//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the Context Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace ffff
{
    using System;
    using Apex.AI;
    using Apex.AI.Components;
    using UnityEngine;

    public class BasicContextProvider : MonoBehaviour, IContextProvider
    {
        private IAIContext _context;

        private void Awake()
        {
            _context = new BasicContext();
        }

        public IAIContext GetContext(Guid aiId)
        {
            return _context;
        }
    }
}